# Site settings
domain: "2RD.top"
url: "https://2rd.top"

# main settings
main_title: "Linktree"
main_description: "‡∏£‡∏ß‡∏°‡∏•‡∏¥‡∏á‡∏Ñ‡πå‡πÇ‡∏õ‡∏£‡πÑ‡∏ü‡∏•‡πå‡πÇ‡∏ã‡πÄ‡∏ä‡∏µ‡∏¢‡∏•‡∏°‡∏µ‡πÄ‡∏î‡∏µ‡∏¢‡∏ó‡∏±‡πâ‡∏á‡∏´‡∏°‡∏î‡∏Ç‡∏≠‡∏á‡∏ú‡∏°"
main_ogm: "/images/2rd_ogm.png"

# mcpe settings
mcpe_url: "/mcpe"
mcpe_title: "‡∏°‡πá‡∏≠‡∏î‡πÑ‡∏°‡∏ô‡πå‡∏Ñ‡∏£‡∏≤‡∏ü‡∏ï‡πå‡πÄ‡∏ö‡∏î‡∏£‡πá‡∏≠‡∏Å"
mcpe_description: "ü§£ ‡∏ó‡∏≥‡∏ï‡∏≤‡∏°‡∏≠‡∏≤‡∏£‡∏°‡∏ì‡πå ‡πÑ‡∏°‡πà‡∏°‡∏µ‡∏≠‡∏≤‡∏£‡∏°‡∏ì‡πå‡∏Å‡πá‡πÑ‡∏°‡πà‡∏ó‡∏≥ ü§£"
mcpe_ogm: "/images/mcpe_ogm.png"

# hytale settings
hytale_url: "/hytale"
hytale_title: "‡∏°‡πá‡∏≠‡∏î‡πÑ‡∏Æ‡πÄ‡∏ó‡∏•"
hytale_description: "ü§£ ‡∏ó‡∏≥‡∏ï‡∏≤‡∏°‡∏≠‡∏≤‡∏£‡∏°‡∏ì‡πå ‡πÑ‡∏°‡πà‡∏°‡∏µ‡∏≠‡∏≤‡∏£‡∏°‡∏ì‡πå‡∏Å‡πá‡πÑ‡∏°‡πà‡∏ó‡∏≥ ü§£"
hytale_ogm: "/images/hytale_ogm.png"

# 404 settings
404_title: "404 PAGE NOT FOUND"
404_description: "‡πÑ‡∏ã‡∏ï‡πå‡∏ó‡∏µ‡πà‡∏Å‡πç‡∏≤‡∏´‡∏ô‡∏î‡∏Ñ‡πà‡∏≤‡∏ï‡∏≤‡∏°‡∏ó‡∏µ‡πà‡∏≠‡∏¢‡∏π‡πà‡∏ô‡∏µ‡πâ‡πÑ‡∏°‡πà ‡∏°‡∏µ‡πÑ‡∏ü‡∏•‡πå‡∏ó‡∏µ‡πà‡∏£‡πâ‡∏≠‡∏á‡∏Ç‡∏≠"


# User settings
username: "2RD"
email: "contact@2rd.top"
footer: "<p class='footer'>Built by <a href='URL_PLACEHOLDER' target='_top' rel='noopener'>USER_PLACEHOLDER</a> and <a href='https://littlelink.io/' target='_blank' rel='noopener'>LittleLink</a>.</p>"

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
