# Site settings
domain: "2RD.top"
url: "https://2rd.top"
title: "Linktree"
description: "‡∏£‡∏ß‡∏°‡∏•‡∏¥‡∏á‡∏Ñ‡πå‡πÇ‡∏õ‡∏£‡πÑ‡∏ü‡∏•‡πå‡πÇ‡∏ã‡πÄ‡∏ä‡∏µ‡∏¢‡∏•‡∏°‡∏µ‡πÄ‡∏î‡∏µ‡∏¢‡∏ó‡∏±‡πâ‡∏á‡∏´‡∏°‡∏î‡∏Ç‡∏≠‡∏á‡∏ú‡∏°"
ogm: "/images/2rd_ogm.png"
mods_url: "/mods"
mods_title: "‡∏°‡πá‡∏≠‡∏î‡∏°‡∏≤‡∏¢‡∏Ñ‡∏£‡∏≤‡∏ü"
mods_description: "ü§£ ‡∏ó‡∏≥‡∏ï‡∏≤‡∏°‡∏≠‡∏≤‡∏£‡∏°‡∏ì‡πå ‡πÑ‡∏°‡πà‡∏°‡∏µ‡∏≠‡∏≤‡∏£‡∏°‡∏ì‡πå‡∏Å‡πá‡πÑ‡∏°‡πà‡∏ó‡∏≥ ü§£"
mods_ogm: "/images/mods_ogm.png"
404_title: "404 PAGE NOT FOUND"
404_description: "‡πÑ‡∏ã‡∏ï‡πå‡∏ó‡∏µ‡πà‡∏Å‡πç‡∏≤‡∏´‡∏ô‡∏î‡∏Ñ‡πà‡∏≤‡∏ï‡∏≤‡∏°‡∏ó‡∏µ‡πà‡∏≠‡∏¢‡∏π‡πà‡∏ô‡∏µ‡πâ‡πÑ‡∏°‡πà ‡∏°‡∏µ‡πÑ‡∏ü‡∏•‡πå‡∏ó‡∏µ‡πà‡∏£‡πâ‡∏≠‡∏á‡∏Ç‡∏≠"
urlc: https://c.2rd.top


# User settings
username: "2RD"
email: "contact@2rd.top"
# footer: "<p>&copy;2025 <a href='URL_PLACEHOLDER' rel='noopener'>USER_PLACEHOLDER</a>. Build your own by forking <a href='https://littlelink.io/' target='_blank' rel='noopener'>LittleLink</a>.</p>"
footer: "<p>&copy;2026 USER_PLACEHOLDER. ‡∏™‡∏á‡∏ß‡∏ô‡∏•‡∏¥‡∏Ç‡∏™‡∏¥‡∏ó‡∏ò‡∏¥‡πå."

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
